name: Deploy Databricks Bundle

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (dev or prd)"
        required: true
        type: choice
        options:
          - dev
          - prd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Select branch based on environment
        id: set_branch
        run: |
          if [ "${{ github.event.inputs.environment }}" = "dev" ]; then
            echo "BRANCH=develop" >> $GITHUB_ENV
          else
            echo "BRANCH=main" >> $GITHUB_ENV
          fi

      - name: Checkout correct branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Set Databricks credentials
        run: |
          if [ "${{ github.event.inputs.environment }}" = "dev" ]; then
            echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST_DEV }}" >> $GITHUB_ENV
            echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN_DEV }}" >> $GITHUB_ENV
          else
            echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST_PRD }}" >> $GITHUB_ENV
            echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN_PRD }}" >> $GITHUB_ENV
          fi

      - name: Deploy bundle
        env:
          DATABRICKS_HOST: ${{ env.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ env.DATABRICKS_TOKEN }}
        run: |
          databricks bundle deploy -e ${{ github.event.inputs.environment }}
