name: Deploy Databricks Bundle

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (dev or prd)"
        required: true
        type: choice
        options:
          - dev
          - prd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Select branch based on environment
        id: set_branch
        run: |
          if [ "${{ github.event.inputs.environment }}" = "dev" ]; then
            echo "BRANCH=develop" >> $GITHUB_ENV
          else
            echo "BRANCH=main" >> $GITHUB_ENV
          fi

      - name: Checkout correct branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy Databricks bundle
        env:
          DATABRICKS_HOST: ${{ github.event.inputs.environment == 'dev' && secrets.DATABRICKS_HOST || secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ github.event.inputs.environment == 'dev' && secrets.DATABRICKS_TOKEN || secrets.DATABRICKS_TOKEN }}
          HEVY_API_KEY: ${{ github.event.inputs.environment == 'dev' && secrets.HEVY_API_KEY || secrets.HEVY_API_KEY }}
        run: |
          databricks bundle deploy --target ${{ github.event.inputs.environment }}
